name: unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: lint
      run: CHECK_FORMAT=1 ./run_clang_format.sh
      continue-on-error: true

    - name: run unit tests
      run: bazel test //test:all --test_tag_filters=-vcan
    
    - name: build release
      run: bazel build //:release

    - name: upload release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bazel-bin/iso14229.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

