name: release

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build release
      run: bazel build //:release

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: >-
        gh release create ${{ github.ref_name }}
        "bazel-bin/iso14229.zip#iso14229.zip"
        --generate-notes
        --title "${{ github.ref_name }}"
